# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180317_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
